### ISSUE TITLE
Show Grade column on edit.php for user's own posts

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/wp-grade-comments#7]
From user request:

> Will it be possible for grades to be displayed in the wp-admin post list for authors? I used some code to only show users only their own posts in the post list. If the grade column is included here, then it can act as a personal gradebook for student authors.

**Comment by crystalvase** [comment]
i made these changes to enable the first part of this request.

/*\* Admin ********************************************************************/

/**
- Add Grade column to wp-admin Posts list.
  *
- @since 1.0.0
  *
- @param array $columns Column info.
  */
  function olgc_add_grade_column( $columns ) {
  if ( olgc_is_instructor() && olgc_is_author() ) {
      return $columns;
  }
  
  $columns['grade'] = __( 'Grade', 'wp-grade-comments' );
  return $columns;
  }
  add_filter( 'manage_post_posts_columns', 'olgc_add_grade_column' );

/**
- Content of the Grade column.
  *
- @since 1.0.0
  *
- @param string $column_name Name of the current column.
- @param int    $post_id     ID of the post for the current row.
  */
  function olgc_add_grade_column_content( $column_name, $post_id ) {
  if ( olgc_is_instructor() && olgc_is_author() ) {
      return;
  }
  
  if ( 'grade' !== $column_name ) {
      return;
  }
  
  // Find the first available grade on a post comment.
  $comments = get_comments( array(
      'post_id' => $post_id,
  ) );
  
  foreach ( $comments as $comment ) {
      $grade = get_comment_meta( $comment->comment_ID, 'olgc_grade', true );
  
  ```
  if ( $grade ) {
      echo esc_html( $grade );
      break;
  }
  ```
  
  }
  }
  add_action( 'manage_post_posts_custom_column', 'olgc_add_grade_column_content', 10, 2 );

**Comment by crystalvase** [comment]
i'm using this code in my theme functions.php file for the second part

---

/**
- Show only the Posts WRITTEN BY the current logged user
- Runs only for the Author role.
  */

add_filter('pre_get_posts', 'posts_for_current_author');

function posts_for_current_author($query) {
    global $pagenow;

```
if( 'edit.php' != $pagenow || !$query->is_admin )
    return $query;

if( !current_user_can( 'manage_options' ) ) {
    global $user_ID;
    $query->set('author', $user_ID );
}
return $query;
```

}

**Comment by boonebgorges** [comment]
Thanks for the suggestions and the code! The second part is not really within the scope of this plugin - if we needed a real "gradebook", I'd argue it should be somewhere other than `edit.php` - but the first part is a good idea. I'm going to make it a bit more sophisticated, so that you only see the column when there are grades to show, and so that you only see your own grades.
